- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.zshenv:
      path: zsh/.zshenv
      force: true
    ~/.config/zsh: zsh
    ~/.tmux.conf: tmux/.tmux.conf
    ~/.config/bash: bash
    ~/.local/share/tmux: tpm
    # ~/.config/tmux/plugins: tpm
- shell:
  - git submodule sync --recursive