- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:

    # vim
    ~/.vim: vim
    ~/.vimrc: vim/vimrc

    # bash
    ~/.bash: bash
    ~/.bash_profile: bash/bash_profile
    ~/.bashrc: bash/bashrc
    
    # zsh

    # git

- shell:
  - git submodule sync --recursive
  - git update-submodules
  - >
    git cleanall -f
    vim/pack/vendor/start/
    zsh/plugins/