- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:

    # vim
    ~/.vim: vim
    ~/.vimrc: vim/vimrc

    # Tmux
    ~/.tmux.conf: tmux/tmux.conf
    ~/.tmux/plugins: tmux/plugins
    ~/.tmux/plugins/tpm: tmux/tpm

    #ZSH
    ~/.zshrc: zsh/zshrc
    ~/.oh-my-zsh/themes: zsh/themes

    # bash
    ~/.bash:
      force: true
      path: bash
    ~/.bashrc: 
      force: true
      path: bash/bashrc


- shell:
  - git submodule sync --recursive
