- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:

    # vim
    ~/.vim: vim
    ~/.vimrc: vim/vimrc

    # Tmux
    ~/.tmux.conf: tmux/tmux.conf
    ~/.tmux/plugins/tpm: tmux/tpm

    # bash
    ~/.bash:
      force: true
      path: bash
    ~/.bashrc: 
      force: true
      path: bash/bashrc
    
    # zsh

    # git

- shell:
  - git submodule sync --recursive
